### ISSUE TITLE
File not generating on linux

### ISSUE THREAD

**Issue by test23345** [Krutoy242/mc-benchmark#2]
I installed node and tried to execute the program in my modpack's folder but it just doesn't seem to work, no log file no matter what I do.

**Comment by Krutoy242** [comment]
Does you installed node correctly? Can you for example check `node --version`?

**Comment by test23345** [comment]
Node Version is 18.14.0

**Comment by Krutoy242** [comment]
Seems like on Linux path to executable is wrong.
You probably need to call `index.js` file directly. Find where mc-benchmark is installed and run `node "/full/path/mc-benchmark/index.js"`

**Comment by test23345** [comment]
Is there anything special I might have to do to install mc-benchmark on certain versions of linux, I can't seem to find the file path.

**Comment by Krutoy242** [comment]
Sorry, I don't have Linux and don't know where Node install global packages here.

**Comment by test23345** [comment]
But if I just followed the instructions on windows it should work right?

**Comment by test23345** [comment]
I don't have the dependency lodash, is there anywhere I can get it?

**Comment by Krutoy242** [comment]
> But if I just followed the instructions on windows it should work right?

I don't know. I never used Linux before and don't know how node works on Linux.

**Comment by Krutoy242** [comment]
> I don't have the dependency lodash, is there anywhere I can get it?

Node always install app required dependencies by itself, no user actions required.

**Comment by test23345** [comment]
I got it to work, but I am confused by making the charts.

**Comment by Krutoy242** [comment]
> I got it to work, but I am confused by making the charts.

How did you confused?

**Comment by Krutoy242** [comment]
Im closing issue since no additional info provided. Feel free to write and i will open again!
