### ISSUE TITLE
Can't open input file

### ISSUE THREAD

**Issue by NFLD99** [Krutoy242/mc-benchmark#3]
\logs> npx mc-benchmark
🔹 Opening debug.log  ✔
🛑 Can't open input file "logs/debug.log". Use option "--input=path/to/debug.log"

[debug.log](https://github.com/user-attachments/files/17452291/debug.log)
this is a forge 1.20.1 debug file if that matters

**Comment by Krutoy242** [comment]
This tool is for minecraft 1.12.2. Its stated in readme.
![image](https://github.com/user-attachments/assets/53bcfef4-dfaf-4fef-9501-ba9353907282)

**Comment by NFLD99** [comment]
ah i missed that, know any 1.20.1 versions we can use?

**Comment by Krutoy242** [comment]
No. I don't know any.
